# Understanding Faiss

In [2]:
# #Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

In [3]:
# import pandas 
import pandas as pd 

In [4]:
df = pd.read_csv("FAISS_text.csv")

In [5]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [6]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

C:\Users\rangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

C:\Users\rangi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\rangi\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Stor

In [8]:
vectors

array([[-0.00247383,  0.03626734, -0.05290458, ..., -0.09152356,
        -0.03969998, -0.04330488],
       [-0.03357266,  0.00980517, -0.03250129, ..., -0.05165472,
         0.02245888, -0.03156181],
       [-0.0186533 , -0.04051308, -0.01235395, ...,  0.00610585,
        -0.07179648,  0.02773854],
       ...,
       [-0.00066459,  0.04252126, -0.05645507, ...,  0.0131547 ,
        -0.03183562, -0.04357665],
       [-0.03317156,  0.03252463, -0.0248484 , ...,  0.01174414,
         0.05747123,  0.00571026],
       [-0.00166396,  0.00413828, -0.04597078, ...,  0.02008535,
         0.05656246, -0.00161596]], shape=(8, 768), dtype=float32)

In [9]:
vectors.shape

(8, 768)

In [10]:
vectors[0]

array([-2.47383164e-03,  3.62673439e-02, -5.29045761e-02, -2.17347927e-02,
        1.41723882e-02, -1.01593044e-03,  2.23636348e-02,  3.65196355e-02,
        3.80901322e-02,  5.22007374e-03, -3.00865136e-02,  2.05454463e-03,
        1.08502693e-02, -8.49088281e-02, -5.57265570e-03, -6.06598780e-02,
        2.32009194e-03, -1.51409274e-02,  1.20671233e-02,  1.98904686e-02,
       -1.27935903e-02, -2.72811390e-02, -3.31879072e-02,  3.40647250e-03,
        8.41179024e-03, -1.94853730e-02,  4.88132276e-02,  2.24118959e-02,
        4.53466848e-02, -5.90892285e-02, -9.13183093e-02, -1.22327765e-03,
       -4.05045785e-02,  8.67172424e-03,  1.26565340e-06, -1.92451607e-02,
       -3.20658758e-02, -4.08173054e-02,  8.79176781e-02, -1.52631411e-02,
        1.09909568e-02, -4.47978564e-02, -4.74823918e-03,  3.52632888e-02,
        1.31070949e-02,  1.09944157e-02, -3.45760910e-03,  9.12348777e-02,
        5.68809398e-02,  4.82893512e-02, -4.51442227e-03,  3.58451083e-02,
       -2.44209617e-02, -

In [11]:
dim = vectors.shape[1]

In [12]:
dim

768

In [15]:
import faiss
index = faiss.IndexFlatL2(dim)

In [16]:
index


<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002CCE7C8D3B0> >

In [17]:
index.add(vectors)

In [18]:
search_query = "An apple a day keeps doctor away"

In [19]:
vec = encoder.encode(search_query)

In [20]:
vec.shape

(768,)

In [21]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [22]:
svec.shape

(1, 768)

In [23]:
index.search(svec, k=2)

(array([[1.3908101, 1.7193401]], dtype=float32), array([[1, 0]]))

In [24]:
dis, I = index.search(svec, k=2)

In [26]:
dis

array([[1.3908101, 1.7193401]], dtype=float32)

In [27]:
I

array([[1, 0]])

In [29]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health